trigger:
  branches:
    include:
      - main

pool:
  name: Infra_pool

variables:
  workingPath: $(System.DefaultWorkingDirectory)/Prod

stages:

# ---------------- Stage 1: Terraform Init + Plan ----------------
- stage: TerraformInitPlan
  displayName: "Terraform Init & Plan"
  jobs:
  - job: InitPlan
    displayName: "Terraform Init & Plan Job"
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(workingPath)'
        backendServiceArm: 'InfraConnection'
        backendAzureRmResourceGroupName: 'rg-puneet'
        backendAzureRmStorageAccountName: 'statepuneet'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(workingPath)'
        environmentServiceNameAzureRM: 'InfraConnection'

# ---------------- Stage 2: Cost Estimation (Infracost) ----------------
- stage: CostEstimation
  displayName: "Infrastructure Cost Estimation"
  dependsOn: TerraformInitPlan
  jobs:
  - job: InfracostJob
    displayName: "Infracost Breakdown"
    steps:
    - script: |
        curl -fsSL https://github.com/infracost/infracost/releases/latest/download/infracost-darwin-arm64.tar.gz -o infracost.tar.gz
        mkdir infracost-bin
        tar -xzf infracost.tar.gz -C infracost-bin
        chmod +x infracost-bin/infracost
        infracost-bin/infracost --version
        infracost-bin/infracost breakdown \
          --path $(workingPath) \
          --format table
      displayName: "Run Infracost"
      env:
        INFRACOST_API_KEY: $(INFRACOST_API_KEY)




# ---------------- Stage 3: Security Scan (tfsec) ----------------
- stage: SecurityScan
  displayName: "Terraform Security Scan"
  dependsOn: TerraformInitPlan
  jobs:
  - job: TfsecScan
    displayName: "Run tfsec"
    steps:
    - script: |
        curl -fsSL https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-darwin-arm64 -o tfsec
        chmod +x tfsec
        ./tfsec $(workingPath)
      displayName: "tfsec scan"


# ---------------- Stage 4: Manual Validation ----------------
- stage: ManualValidation
  displayName: "Manual Approval"
  dependsOn:
    - CostEstimation
    - SecurityScan
  jobs:
  - job: ManualApproval
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'puneet.070402@gmail.com'
        approvers: 'puneet.070402@gmail.com'

# ---------------- Stage 5: Terraform Apply ----------------
- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: ManualValidation
  condition: succeeded()
  jobs:
  - job: Apply
    steps:

    - task: TerraformTask@5
      displayName: 'Terraform Init (Reconfigure)'
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-reconfigure'
        workingDirectory: '$(workingPath)'
        backendServiceArm: 'InfraConnection'
        backendAzureRmResourceGroupName: 'rg-puneet'
        backendAzureRmStorageAccountName: 'statepuneet'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        workingDirectory: '$(workingPath)'
        environmentServiceNameAzureRM: 'InfraConnection'
