trigger:
  branches:
    include:
      - main

pool:
  name: projectpool

variables:
  Directory_path: '$(System.DefaultWorkingDirectory)/Prod'
  service_connec: 'workload_federation connection'

  
steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Directory_path)'
    backendServiceArm: '$(service_connec)'
    backendAzureRmResourceGroupName: 'rg_Puneet'
    backendAzureRmStorageAccountName: 'statefile123'
    backendAzureRmContainerName: 'statecontainer'
    backendAzureRmKey: 'prod.terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(Directory_path)'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(Directory_path)'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: '$(service_connec)'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(Directory_path)'
    environmentServiceNameAzureRM: '$(service_connec)'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(Directory_path)'
    environmentServiceNameAzureRM: '$(service_connec)'
